name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  tests-sqlite:
    name: Tests (SQLite)
    runs-on: ubuntu-latest
    env:
      DB_LEGACY_SQLITE: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run pytest
        run: pytest
  tests-mariadb:
    name: Tests (MariaDB)
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.11
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: tt_game_liste
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_LEGACY_SQLITE: "0"
      DB_HOST: 127.0.0.1
      DB_PORT: "3306"
      DB_NAME: tt_game_liste
      DB_USER: root
      DB_PASSWORD: root
      DB_CONNECT_TIMEOUT: "10"
      DB_READ_TIMEOUT: "30"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Wait for MariaDB
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; then
              break
            fi
            sleep 2
          done
      - name: Run pytest
        run: pytest
